# Generated by Django 2.2.11 on 2020-04-07 15:24

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books_recsys_app', '0009_userprofile_arrayratedmoviesindxs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='array',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='array',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='arrayratedmoviesindxs',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastrecs',
            field=jsonfield.fields.JSONField(),
        ),
    ]
